import Erdos1016.Probability.Cylinders.CutParity
import Erdos1016.Probability.Cylinders.RankOnePairBound

set_option autoImplicit false

/-!
# Actual cut-coordinate cylinders and second moments

Section 10 constrains the physical cut-edge coordinates themselves. This
module gives their exact marginal and pair probabilities under the uniform
physical cycle-space law. The pair estimate reduces to a rank-one bound for
the common constraint space. The rank/partner estimates needed to verify
that premise for a graph family remain graph-specific.
-/

noncomputable section

namespace Erdos1016.Proof.ActualCutPairProbability

open Erdos1016
open Erdos1016.Proof.ActualCutCycleCylinder
open Erdos1016.Proof.GraphicalThreshold
open Erdos1016.Proof.ManyCyclicRegionCutCylinders

local notation "𝔽" => ZMod 2

variable (G : PhysicalGraph)

private theorem vectorProbability_eq_eventProbability
    (P : G.CycleSpace → Prop) :
    vectorProbability P = eventProbability P := by
  classical
  letI : Nonempty G.CycleSpace := ⟨0⟩
  unfold vectorProbability eventProbability
    Erdos1016.Proof.FinitePaleyZygmund.probability
  simp [Nat.card_eq_fintype_card, Fintype.card_subtype]

/-- Constraint space generated by the coordinates of a physical cut. -/
def cutConstraintSpace (U : Finset G.Vertex) :
    Submodule 𝔽 (Module.Dual 𝔽 G.CycleSpace) :=
  outgoingCutConstraintSpace G (G.cutEdges U)

/-- The actual cut-coordinate zero event is exactly the zero cylinder of its
coordinate constraint space. -/
theorem cutCoordinatesZero_iff_zeroCylinder
    (U : Finset G.Vertex) (x : G.CycleSpace) :
    cutCoordinatesZero G U x ↔ zeroCylinder (cutConstraintSpace G U) x := by
  rw [cutConstraintSpace]
  exact (outgoingCut_zero_iff G (G.cutEdges U) x).symm

/-- Exact marginal probability for zero on every actual cut edge. -/
theorem cutCoordinatesZero_probability
    (U : Finset G.Vertex) :
    eventProbability (cutCoordinatesZero G U) =
      1 / (2 : ℝ) ^ Module.finrank 𝔽 (cutConstraintSpace G U) := by
  rw [← vectorProbability_eq_eventProbability G]
  have heq : cutCoordinatesZero G U = zeroCylinder (cutConstraintSpace G U) := by
    funext x
    exact propext (cutCoordinatesZero_iff_zeroCylinder G U x)
  rw [heq]
  exact zeroCylinder_probability (cutConstraintSpace G U)



/-- Ordinary-pair bound for the actual cut events, provided the shared
coordinate constraints have rank at most one. -/
theorem cutCoordinatesZero_pair_le_twice_product
    (U V : Finset G.Vertex)
    (hrank : Module.finrank 𝔽
      ↥(cutConstraintSpace G U ⊓ cutConstraintSpace G V) ≤ 1) :
    eventProbability (fun x : G.CycleSpace =>
      cutCoordinatesZero G U x ∧ cutCoordinatesZero G V x) ≤
      2 * eventProbability (cutCoordinatesZero G U) *
        eventProbability (cutCoordinatesZero G V) := by
  have hL : vectorProbability (cutCoordinatesZero G U) =
      vectorProbability (zeroCylinder (cutConstraintSpace G U)) := by
    calc
      vectorProbability (cutCoordinatesZero G U) =
          eventProbability (cutCoordinatesZero G U) :=
        vectorProbability_eq_eventProbability G _
      _ = 1 / (2 : ℝ) ^ Module.finrank 𝔽 (cutConstraintSpace G U) :=
        cutCoordinatesZero_probability G U
      _ = eventProbability (zeroCylinder (cutConstraintSpace G U)) := by
        rw [← vectorProbability_eq_eventProbability G _]
        rw [zeroCylinder_probability]
      _ = vectorProbability (zeroCylinder (cutConstraintSpace G U)) :=
        (vectorProbability_eq_eventProbability G _).symm
  have hM : vectorProbability (cutCoordinatesZero G V) =
      vectorProbability (zeroCylinder (cutConstraintSpace G V)) := by
    calc
      vectorProbability (cutCoordinatesZero G V) =
          eventProbability (cutCoordinatesZero G V) :=
        vectorProbability_eq_eventProbability G _
      _ = 1 / (2 : ℝ) ^ Module.finrank 𝔽 (cutConstraintSpace G V) :=
        cutCoordinatesZero_probability G V
      _ = eventProbability (zeroCylinder (cutConstraintSpace G V)) := by
        rw [← vectorProbability_eq_eventProbability G _]
        rw [zeroCylinder_probability]
      _ = vectorProbability (zeroCylinder (cutConstraintSpace G V)) :=
        (vectorProbability_eq_eventProbability G _).symm
  have hpair : vectorProbability (fun x : G.CycleSpace =>
      cutCoordinatesZero G U x ∧ cutCoordinatesZero G V x) =
      vectorProbability (fun x : G.CycleSpace =>
        zeroCylinder (cutConstraintSpace G U) x ∧
          zeroCylinder (cutConstraintSpace G V) x) := by
    congr 1
    funext x
    exact propext (Iff.intro
      (fun h => ⟨(cutCoordinatesZero_iff_zeroCylinder G U x).1 h.1,
                  (cutCoordinatesZero_iff_zeroCylinder G V x).1 h.2⟩)
      (fun h => ⟨(cutCoordinatesZero_iff_zeroCylinder G U x).2 h.1,
                  (cutCoordinatesZero_iff_zeroCylinder G V x).2 h.2⟩))
  calc
    eventProbability (fun x : G.CycleSpace =>
        cutCoordinatesZero G U x ∧ cutCoordinatesZero G V x) =
      vectorProbability (fun x : G.CycleSpace =>
        cutCoordinatesZero G U x ∧ cutCoordinatesZero G V x) :=
      (vectorProbability_eq_eventProbability G _).symm
    _ = vectorProbability (fun x : G.CycleSpace =>
        zeroCylinder (cutConstraintSpace G U) x ∧
          zeroCylinder (cutConstraintSpace G V) x) := hpair
    _ ≤ 2 * vectorProbability (zeroCylinder (cutConstraintSpace G U)) *
          vectorProbability (zeroCylinder (cutConstraintSpace G V)) :=
      zeroCylinder_pair_probability_le_twice_product
        (cutConstraintSpace G U) (cutConstraintSpace G V) hrank
    _ = 2 * eventProbability (cutCoordinatesZero G U) *
          eventProbability (cutCoordinatesZero G V) := by
      rw [← hL, ← hM]
      simp only [vectorProbability_eq_eventProbability G]



end Erdos1016.Proof.ActualCutPairProbability

end
