import Erdos1016.Probability.Cylinders.IncidentTripleEvents
import Erdos1016.CycleSpace.Graphical.TripleStarReduction
import Erdos1016.Probability.Cylinders.SubspacePartnerCount

set_option autoImplicit false

/-!
# Transfer triple-star bounds to the cylinder constraint spaces

The second-moment argument counts intersections of the affine constraint
spaces of selected triples.  Those spaces are generated by the three edge
coordinates, so when each triple is incident to its marked vertex they lie in
that vertex's star space.  This file transfers a three-star dimension bound
to the common part of three selected-triple constraint spaces.
-/

noncomputable section

namespace Erdos1016.Proof.GraphicalTripleConstraintIntersection

open Erdos1016
open Erdos1016.Proof.ActiveTripleBridge
open Erdos1016.Proof.GraphicalCommonInformation
open Erdos1016.Proof.GraphicalTripleReduction
open Erdos1016.Proof.PartnerCounting

local notation "F₂" => ZMod 2

/-- The common part of three selected-triple constraint spaces is contained
in the intersection of the corresponding three vertex-star spaces. -/
theorem tripleConstraint_intersection_le_tripleStar
    (G : PhysicalGraph) (e₁ e₂ e₃ : Fin 3 → G.Edge)
    (u v w : G.Vertex)
    (h₁ : ∀ i, G.incident (e₁ i) u)
    (h₂ : ∀ i, G.incident (e₂ i) v)
    (h₃ : ∀ i, G.incident (e₃ i) w) :
    TripleIntersection (tripleConstraintSpace G e₁)
        (tripleConstraintSpace G e₂) (tripleConstraintSpace G e₃) ≤
      tripleStarSpace G u v w := by
  have hs₁ : tripleConstraintSpace G e₁ ≤ vertexStarSpace G u :=
    tripleObservation_dualRange_le_vertexStarSpace G u e₁ h₁
  have hs₂ : tripleConstraintSpace G e₂ ≤ vertexStarSpace G v :=
    tripleObservation_dualRange_le_vertexStarSpace G v e₂ h₂
  have hs₃ : tripleConstraintSpace G e₃ ≤ vertexStarSpace G w :=
    tripleObservation_dualRange_le_vertexStarSpace G w e₃ h₃
  intro f hf
  change f ∈ (tripleConstraintSpace G e₁ ⊓
      tripleConstraintSpace G e₂) ∧ f ∈ tripleConstraintSpace G e₃ at hf
  rcases hf with ⟨⟨hf₁, hf₂⟩, hf₃⟩
  change f ∈ (vertexStarSpace G u ⊓ vertexStarSpace G v) ∧
      f ∈ vertexStarSpace G w
  exact ⟨⟨hs₁ hf₁, hs₂ hf₂⟩, hs₃ hf₃⟩

/-- If the graph's three-star intersection has dimension at most one, so does
the common space of any three incident selected-triple cylinders. -/
theorem tripleConstraint_intersection_finrank_le_one
    (G : PhysicalGraph) (e₁ e₂ e₃ : Fin 3 → G.Edge)
    (u v w : G.Vertex)
    (h₁ : ∀ i, G.incident (e₁ i) u)
    (h₂ : ∀ i, G.incident (e₂ i) v)
    (h₃ : ∀ i, G.incident (e₃ i) w)
    (hstar : Module.finrank F₂ (tripleStarSpace G u v w) ≤ 1) :
    Module.finrank F₂
      (TripleIntersection (tripleConstraintSpace G e₁)
        (tripleConstraintSpace G e₂) (tripleConstraintSpace G e₃)) ≤ 1 := by
  exact (Submodule.finrank_mono
    (tripleConstraint_intersection_le_tripleStar G e₁ e₂ e₃ u v w h₁ h₂ h₃)).trans
    hstar

end Erdos1016.Proof.GraphicalTripleConstraintIntersection
