import Erdos1016.Probability.Cylinders.Affine
import Erdos1016.CycleSpace.Graphical.VertexStarSpaces

set_option autoImplicit false

/-!
# Zero-coordinate cylinders and constraint ranks

For a uniformly sampled vector, requiring a family of linear functionals to
vanish has probability `2 ^ (-rank)`.  This module packages the cut-size lower
bound and the pair-intersection rank formula independently of a graph model.
The graph-specific step is to identify the chosen outgoing cut coordinates
with a finite family of functionals on the cycle space.
-/

noncomputable section
open scoped BigOperators

namespace Erdos1016.Proof.ManyCyclicRegionCutCylinders

abbrev F₂ := ZMod 2

variable {W : Type*} [AddCommGroup W] [Module F₂ W]
  [FiniteDimensional F₂ W] [Fintype W] [Fintype F₂]

/-- The event that a uniform vector is annihilated by every constraint in `L`.
Here `L` is a subspace of the dual space of `W`. -/
def zeroCylinder (L : Submodule F₂ (Module.Dual F₂ W)) (x : W) : Prop :=
  ∀ f : Module.Dual F₂ W, f ∈ L → f x = 0

/-- Uniform probability on vectors in `W`. -/
def vectorProbability (P : W → Prop) : ℝ := by
  classical
  exact (Nat.card {x : W // P x} : ℝ) / (Nat.card W : ℝ)

/-- The linear constraints generated by a finite family of functionals. -/
def constraintSpan (C : Finset (Module.Dual F₂ W)) :
    Submodule F₂ (Module.Dual F₂ W) :=
  Submodule.span F₂ (C : Set (Module.Dual F₂ W))

/-- The rank of a finite family of constraints is at most its size. -/
theorem constraintSpan_finrank_le_card (C : Finset (Module.Dual F₂ W)) :
    Module.finrank F₂ (constraintSpan C) ≤ C.card := by
  exact finrank_span_finset_le_card C

/-- Vanishing on the span is equivalent to vanishing on each named
functional. -/
theorem zeroCylinder_constraintSpan_iff
    (C : Finset (Module.Dual F₂ W)) (x : W) :
    zeroCylinder (constraintSpan C) x ↔ ∀ f ∈ C, f x = 0 := by
  constructor
  · intro h f hf
    exact h f (Submodule.subset_span hf)
  · intro h f hf
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hf
    · intro g hg
      exact h g hg
    · simp
    · intro g h hg hh hgv hhv
      simp [hgv, hhv]
    · intro a g hg hgv
      simp [hgv]

/-- Restrict the evaluation functional of a vector to the constraint space. -/
def evaluateConstraints (L : Submodule F₂ (Module.Dual F₂ W)) :
    W →ₗ[F₂] Module.Dual F₂ L :=
  L.dualRestrict.comp (Module.evalEquiv F₂ W).toLinearMap

/-- The affine cylinder assigning prescribed values to all constraints in
`L`. -/
def constraintCylinder (L : Submodule F₂ (Module.Dual F₂ W))
    (a : Module.Dual F₂ L) (x : W) : Prop :=
  evaluateConstraints L x = a

private theorem evaluateConstraints_surjective
    (L : Submodule F₂ (Module.Dual F₂ W)) :
    Function.Surjective (evaluateConstraints L) := by
  intro a
  obtain ⟨g, hg⟩ :=
    (Erdos1016.Proof.AffineCylinders.restriction_surjective
      (W := Module.Dual F₂ W) L) a
  obtain ⟨x, hx⟩ := (Module.evalEquiv F₂ W).surjective g
  refine ⟨x, ?_⟩
  change L.dualRestrict (Module.Dual.eval F₂ W x) = a
  rw [← Module.evalEquiv_apply F₂ W x, hx]
  exact hg

private theorem evaluateConstraints_ker_finrank
    (L : Submodule F₂ (Module.Dual F₂ W)) :
    Module.finrank F₂ (LinearMap.ker (evaluateConstraints L)) +
      Module.finrank F₂ L = Module.finrank F₂ W := by
  have h := LinearMap.finrank_range_add_finrank_ker (evaluateConstraints L)
  have hrange : LinearMap.range (evaluateConstraints L) = ⊤ :=
    LinearMap.range_eq_top.2 (evaluateConstraints_surjective L)
  rw [hrange] at h
  simpa [add_comm] using h





private noncomputable def zeroCylinder_equiv_ker
    (L : Submodule F₂ (Module.Dual F₂ W)) :
    {x : W // zeroCylinder L x} ≃ LinearMap.ker (evaluateConstraints L) where
  toFun x := ⟨x.1, by
    change evaluateConstraints L x.1 = 0
    ext f
    simp only [evaluateConstraints, LinearMap.comp_apply,
      Submodule.dualRestrict_apply, Module.Dual.eval_apply,
      LinearMap.zero_apply]
    exact x.2 f f.property⟩
  invFun x := ⟨x.1, by
    intro f hf
    have hx : evaluateConstraints L x.1 = 0 := x.2
    have hval := congrArg (fun q : Module.Dual F₂ L => q ⟨f, hf⟩) hx
    exact hval⟩
  left_inv x := by apply Subtype.ext; rfl
  right_inv x := by apply Subtype.ext; rfl

/-- Every zero-cut cylinder has exact probability `2^-rank(L)`. -/
theorem zeroCylinder_probability (L : Submodule F₂ (Module.Dual F₂ W)) :
    vectorProbability (zeroCylinder L) =
      1 / (2 : ℝ) ^ Module.finrank F₂ L := by
  classical
  have hkerCard : Nat.card {x : W // zeroCylinder L x} =
      2 ^ Module.finrank F₂ (LinearMap.ker (evaluateConstraints L)) := by
    rw [Nat.card_congr (zeroCylinder_equiv_ker L)]
    simpa [F₂] using (Module.natCard_eq_pow_finrank (K := F₂)
      (V := LinearMap.ker (evaluateConstraints L)))
  have hWCard : Nat.card W = 2 ^ Module.finrank F₂ W := by
    simpa [F₂] using (Module.natCard_eq_pow_finrank (K := F₂) (V := W))
  have hdim := evaluateConstraints_ker_finrank L
  unfold vectorProbability
  rw [hkerCard, hWCard]
  have hpow : (2 : ℝ) ^ Module.finrank F₂
      (LinearMap.ker (evaluateConstraints L)) *
      (2 : ℝ) ^ Module.finrank F₂ L =
      (2 : ℝ) ^ Module.finrank F₂ W := by
    rw [← pow_add, hdim]
  have hden : (2 : ℝ) ^ Module.finrank F₂ W ≠ 0 := by positivity
  have hsub : (2 : ℝ) ^ Module.finrank F₂ L ≠ 0 := by positivity
  field_simp
  nlinarith





/-- The intersection of two zero-cut cylinders is the cylinder for the sum
of their constraint spaces. -/
theorem zeroCylinder_inter_iff (L M : Submodule F₂ (Module.Dual F₂ W))
    (x : W) :
    (zeroCylinder L x ∧ zeroCylinder M x) ↔ zeroCylinder (L ⊔ M) x := by
  constructor
  · intro hx f hf
    rcases Submodule.mem_sup.mp hf with ⟨g, hg, h, hh, hadd⟩
    rw [← hadd]
    simp [hx.1 g hg, hx.2 h hh]
  · intro hx
    constructor
    · intro f hf
      exact hx f (Submodule.mem_sup_left hf)
    · intro f hf
      exact hx f (Submodule.mem_sup_right hf)

/-- Pair intersections have the probability dictated by the summed rank, and
the rank of the sum obeys the exact dimension identity with the overlap. -/
theorem zeroCylinder_pair_probability (L M : Submodule F₂ (Module.Dual F₂ W)) :
    vectorProbability (fun x => zeroCylinder L x ∧ zeroCylinder M x) =
      1 / (2 : ℝ) ^ Module.finrank F₂ ↥(L ⊔ M) ∧
    Module.finrank F₂ L + Module.finrank F₂ M =
      Module.finrank F₂ ↥(L ⊔ M) + Module.finrank F₂ ↥(L ⊓ M) := by
  constructor
  · have heq : (fun x : W => zeroCylinder L x ∧ zeroCylinder M x) =
        zeroCylinder (L ⊔ M) := by
      funext x
      exact propext (zeroCylinder_inter_iff L M x)
    rw [heq]
    exact zeroCylinder_probability (L ⊔ M)
  · exact (Submodule.finrank_sup_add_finrank_inf_eq L M).symm

/-- The constraint space generated by the edge-coordinate functionals on a
specified finite cut of a physical graph's cycle space. -/
def outgoingCutConstraintSpace (G : Erdos1016.PhysicalGraph)
    (cut : Finset G.Edge) :
    Submodule F₂ (Module.Dual F₂ G.CycleSpace) :=
  constraintSpan (cut.image
    (Erdos1016.Proof.GraphicalCommonInformation.edgeCoordinate G))

/-- Vanishing on the cut constraint space is exactly vanishing of every
specified outgoing edge coordinate. -/
theorem outgoingCut_zero_iff (G : Erdos1016.PhysicalGraph)
    (cut : Finset G.Edge) (x : G.CycleSpace) :
    zeroCylinder (outgoingCutConstraintSpace G cut) x ↔
      ∀ e ∈ cut, x.1 e = 0 := by
  simpa [outgoingCutConstraintSpace, constraintSpan,
    Erdos1016.Proof.GraphicalCommonInformation.edgeCoordinate] using
    (zeroCylinder_constraintSpan_iff
      (cut.image (Erdos1016.Proof.GraphicalCommonInformation.edgeCoordinate G)) x)



end Erdos1016.Proof.ManyCyclicRegionCutCylinders
