import Mathlib

set_option autoImplicit false

/-!
# Spans of coordinate functionals

For any linear observation map into a finite coordinate space, the span of
the pulled-back coordinate functionals is exactly the image of the dual map.
This is the linear-algebra fact needed to identify a graph's incident-edge
coordinate span with the functionals determined by restriction to its star.
-/

noncomputable section

namespace Erdos1016.Proof.CoordinateFunctionalSpan

variable {F V E : Type*} [Field F]
  [AddCommGroup V] [Module F V]
  [Fintype E] [DecidableEq E]

/-- The coordinate functional on a finite function space. -/
def coordinate (e : E) : Module.Dual F (E → F) :=
  (Pi.basisFun F E).dualBasis e

@[simp] theorem coordinate_apply (e : E) (x : E → F) :
    coordinate (F := F) e x = x e := by
  simp [coordinate, Basis.dualBasis_apply, Pi.basisFun_repr]

/-- Pull back a coordinate functional along a linear observation. -/
def pulledCoordinate (r : V →ₗ[F] (E → F)) (e : E) : Module.Dual F V :=
  r.dualMap (coordinate (F := F) e)

@[simp] theorem pulledCoordinate_apply (r : V →ₗ[F] (E → F))
    (e : E) (v : V) :
    pulledCoordinate r e v = r v e := by
  simp [pulledCoordinate, LinearMap.dualMap_apply]

/-- The full dual image is generated by its pulled-back coordinate
functionals. This formulation works for arbitrary finite coordinate sets and
does not use graph structure. -/
theorem dualMap_range_eq_span_coordinates
    (r : V →ₗ[F] (E → F)) :
    LinearMap.range r.dualMap =
      Submodule.span F (Set.range (pulledCoordinate (F := F) r)) := by
  classical
  apply le_antisymm
  · rintro φ ⟨g, rfl⟩
    have hexpand := Basis.sum_repr ((Pi.basisFun F E).dualBasis) g
    rw [← hexpand]
    simp only [map_sum, map_smul]
    apply Submodule.sum_mem
    intro e he
    apply Submodule.smul_mem
    apply Submodule.subset_span
    exact ⟨e, rfl⟩
  · apply Submodule.span_le.2
    rintro φ ⟨e, rfl⟩
    exact ⟨coordinate (F := F) e, rfl⟩



end Erdos1016.Proof.CoordinateFunctionalSpan
