import Erdos1016.Graph.Multigraph.Basic
import Erdos1016.Probability.Cylinders.CutPairProbabilities
import Erdos1016.CycleSpace.Graphical.DualPullback
import Erdos1016.CycleSpace.Graphical.TripleStarReduction

set_option autoImplicit false

noncomputable section

namespace Erdos1016.Proof.GraphicalActualCutMultigraphBridge

open Erdos1016
open Erdos1016.Proof.ActualCutPairProbability
open Erdos1016.Proof.GraphicalCommonInformation
open Erdos1016.Proof.GraphicalRegionContraction
open Erdos1016.Proof.ManyCyclicRegionCutCylinders
open Erdos1016.Proof.GraphicalTripleReduction

local notation "𝔽" => ZMod 2

/-- Edge-coordinate functionals for a labelled multigraph cycle space. -/
def multiEdgeCoordinate (M : FiniteMultiGraph) (e : M.Edge) :
    M.CycleSpace →ₗ[𝔽] 𝔽 where
  toFun x := x.1 e
  map_add' x y := rfl
  map_smul' a x := rfl

/-- Restriction of an edge word along an injective quotient-edge labelling. -/
def restrictWord {G : PhysicalGraph} (M : FiniteMultiGraph)
    (edgeMap : M.Edge → G.Edge) : G.Word →ₗ[𝔽] M.EdgeWord where
  toFun x e := x (edgeMap e)
  map_add' x y := rfl
  map_smul' a x := rfl

/-- The cycle restriction map, provided the restricted word has zero
multigraph boundary for every ambient cycle. -/
def restrictCycles (G : PhysicalGraph) (M : FiniteMultiGraph)
    (edgeMap : M.Edge → G.Edge)
    (hcycle : ∀ x : G.CycleSpace,
      M.boundary (restrictWord M edgeMap x.1) = 0) :
    G.CycleSpace →ₗ[𝔽] M.CycleSpace where
  toFun x := ⟨restrictWord M edgeMap x.1, hcycle x⟩
  map_add' x y := by
    apply Subtype.ext
    rfl
  map_smul' a x := by
    apply Subtype.ext
    rfl

@[simp] theorem restrictCycles_apply (G : PhysicalGraph) (M : FiniteMultiGraph)
    (edgeMap : M.Edge → G.Edge)
    (hcycle : ∀ x : G.CycleSpace,
      M.boundary (restrictWord M edgeMap x.1) = 0)
    (x : G.CycleSpace) (e : M.Edge) :
    (restrictCycles G M edgeMap hcycle x).1 e = x.1 (edgeMap e) := rfl

/-- Pullback of a quotient multigraph edge-coordinate is the coordinate on
the corresponding original physical edge. -/
theorem multiEdgeCoordinate_pullback (G : PhysicalGraph)
    (M : FiniteMultiGraph) (edgeMap : M.Edge → G.Edge)
    (hcycle : ∀ x : G.CycleSpace,
      M.boundary (restrictWord M edgeMap x.1) = 0)
    (e : M.Edge) :
    dualPullback (restrictCycles G M edgeMap hcycle)
        (multiEdgeCoordinate M e) = edgeCoordinate G (edgeMap e) := by
  ext x
  rfl

/-- The star generated by all labelled edges incident to a multigraph vertex.
Parallel edges remain separate coordinates; loops count as incident. -/
def multiVertexStarSpace (M : FiniteMultiGraph) (q : M.Vertex) :
    Submodule 𝔽 (M.CycleSpace →ₗ[𝔽] 𝔽) :=
  Submodule.span 𝔽 {f | ∃ e : M.Edge,
    (M.src e = q ∨ M.dst e = q) ∧ f = multiEdgeCoordinate M e}

/-- If quotient edges incident to `q` correspond exactly to the actual cut
edges of `U`, and every cut edge is represented, then the quotient star
pulls back to the actual cut-coordinate span. This is the precise coordinate
correspondence needed by the common-information quotient lemma. -/
theorem map_multiVertexStar_eq_cutConstraintSpace
    (G : PhysicalGraph) (M : FiniteMultiGraph)
    (edgeMap : M.Edge → G.Edge) (hcycle : ∀ x : G.CycleSpace,
      M.boundary (restrictWord M edgeMap x.1) = 0)
    (U : Finset G.Vertex) (q : M.Vertex)
    (hincident : ∀ e : M.Edge,
      (M.src e = q ∨ M.dst e = q) ↔ edgeMap e ∈ G.cutEdges U)
    (hcover : ∀ a : G.Edge, a ∈ G.cutEdges U → ∃ e : M.Edge,
      edgeMap e = a) :
    (multiVertexStarSpace M q).map
      (dualPullback (restrictCycles G M edgeMap hcycle)) =
        cutConstraintSpace G U := by
  classical
  rw [multiVertexStarSpace, Submodule.map_span]
  apply congrArg (Submodule.span 𝔽)
  ext f
  constructor
  · rintro ⟨g, ⟨e, he, rfl⟩, rfl⟩
    rw [multiEdgeCoordinate_pullback]
    change edgeCoordinate G (edgeMap e) ∈
      (G.cutEdges U).image (edgeCoordinate G)
    exact Finset.mem_image.mpr
      ⟨edgeMap e, (hincident e).mp he, rfl⟩
  · intro hf
    change f ∈ (G.cutEdges U).image (edgeCoordinate G) at hf
    rcases Finset.mem_image.mp hf with ⟨a, ha, rfl⟩
    obtain ⟨e, heq⟩ := hcover a ha
    subst a
    refine ⟨multiEdgeCoordinate M e, ?_, ?_⟩
    · exact ⟨e, (hincident e).mpr ha, rfl⟩
    · exact (multiEdgeCoordinate_pullback G M edgeMap hcycle e).symm

/-- The common star space at three quotient vertices in a labelled
multigraph. -/
def multiTripleStarSpace (M : FiniteMultiGraph) (u v w : M.Vertex) :
    Submodule 𝔽 (M.CycleSpace →ₗ[𝔽] 𝔽) :=
  subspaceInter (subspaceInter (multiVertexStarSpace M u)
    (multiVertexStarSpace M v)) (multiVertexStarSpace M w)

private theorem map_subspaceInter_eq
    {F X Y : Type*} [Field F] [AddCommGroup X] [Module F X]
    [AddCommGroup Y] [Module F Y]
    (f : X →ₗ[F] Y) (hf : Function.Injective f)
    (A B : Submodule F X) :
    (subspaceInter A B).map f = subspaceInter (A.map f) (B.map f) := by
  ext y
  constructor
  · intro hy
    change ∃ x, x ∈ subspaceInter A B ∧ f x = y at hy
    rcases hy with ⟨x, hx, rfl⟩
    exact ⟨⟨x, hx.1, rfl⟩, ⟨x, hx.2, rfl⟩⟩
  · intro hy
    rcases hy with ⟨hyA, hyB⟩
    change ∃ x, x ∈ A ∧ f x = y at hyA
    change ∃ z, z ∈ B ∧ f z = y at hyB
    rcases hyA with ⟨x, hx, hxy⟩
    rcases hyB with ⟨z, hz, hzy⟩
    have hxz : x = z := hf (hxy.trans hzy.symm)
    subst z
    change ∃ t, t ∈ subspaceInter A B ∧ f t = y
    exact ⟨x, ⟨hx, hz⟩, hxy⟩

private theorem map_multiTripleStar_eq
    (G : PhysicalGraph) (M : FiniteMultiGraph)
    (f : (M.CycleSpace →ₗ[𝔽] 𝔽) →ₗ[𝔽]
      (G.CycleSpace →ₗ[𝔽] 𝔽))
    (hf : Function.Injective f) (u v w : M.Vertex) :
    (multiTripleStarSpace M u v w).map f =
      subspaceInter (subspaceInter ((multiVertexStarSpace M u).map f)
        ((multiVertexStarSpace M v).map f))
        ((multiVertexStarSpace M w).map f) := by
  unfold multiTripleStarSpace
  rw [map_subspaceInter_eq f hf]
  rw [map_subspaceInter_eq f hf]

/-- Multigraph quotient-transfer theorem for three actual cuts.

The edge-incidence and coverage hypotheses make the pullback of each
quotient multigraph star exactly the actual cut-coordinate space; this
correspondence is proved above. The remaining graph-specific inputs are that
cycle restriction is surjective and that the quotient's three-star
intersection has rank at most one. Connected fibers are expected to supply
the first input; a triple-star theorem for connected finite multigraphs
supplies the second. -/
theorem actualCutTripleIntersection_finrank_le_one_of_multigraph_quotient
    (G : PhysicalGraph) (M : FiniteMultiGraph)
    (edgeMap : M.Edge → G.Edge)
    (hcycle : ∀ x : G.CycleSpace,
      M.boundary (restrictWord M edgeMap x.1) = 0)
    (hrestrict : Function.Surjective (restrictCycles G M edgeMap hcycle))
    (U V W : Finset G.Vertex) (u v w : M.Vertex)
    (hUincident : ∀ e : M.Edge,
      (M.src e = u ∨ M.dst e = u) ↔ edgeMap e ∈ G.cutEdges U)
    (hUcover : ∀ a : G.Edge, a ∈ G.cutEdges U → ∃ e : M.Edge,
      edgeMap e = a)
    (hVincident : ∀ e : M.Edge,
      (M.src e = v ∨ M.dst e = v) ↔ edgeMap e ∈ G.cutEdges V)
    (hVcover : ∀ a : G.Edge, a ∈ G.cutEdges V → ∃ e : M.Edge,
      edgeMap e = a)
    (hWincident : ∀ e : M.Edge,
      (M.src e = w ∨ M.dst e = w) ↔ edgeMap e ∈ G.cutEdges W)
    (hWcover : ∀ a : G.Edge, a ∈ G.cutEdges W → ∃ e : M.Edge,
      edgeMap e = a)
    (hrank : Module.finrank 𝔽 (multiTripleStarSpace M u v w) ≤ 1) :
    Module.finrank 𝔽
      (subspaceInter (subspaceInter (cutConstraintSpace G U)
        (cutConstraintSpace G V)) (cutConstraintSpace G W)) ≤ 1 := by
  let r := restrictCycles G M edgeMap hcycle
  have hpull : Function.Injective (dualPullback r) :=
    dualPullback_injective r hrestrict
  have hspace :
      subspaceInter (subspaceInter (cutConstraintSpace G U)
        (cutConstraintSpace G V)) (cutConstraintSpace G W) =
      (multiTripleStarSpace M u v w).map (dualPullback r) := by
    change subspaceInter (subspaceInter (cutConstraintSpace G U)
      (cutConstraintSpace G V)) (cutConstraintSpace G W) =
      (multiTripleStarSpace M u v w).map
        (dualPullback (restrictCycles G M edgeMap hcycle))
    rw [← map_multiVertexStar_eq_cutConstraintSpace G M edgeMap hcycle U u
      hUincident hUcover]
    rw [← map_multiVertexStar_eq_cutConstraintSpace G M edgeMap hcycle V v
      hVincident hVcover]
    rw [← map_multiVertexStar_eq_cutConstraintSpace G M edgeMap hcycle W w
      hWincident hWcover]
    symm
    exact map_multiTripleStar_eq G M
      (dualPullback (restrictCycles G M edgeMap hcycle)) hpull u v w
  rw [hspace]
  have hdim := (Submodule.equivMapOfInjective (dualPullback r)
    hpull (multiTripleStarSpace M u v w)).finrank_eq
  rw [← hdim]
  exact hrank

end Erdos1016.Proof.GraphicalActualCutMultigraphBridge

end
